require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `-D/--display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: true

Metrics/BlockLength:
  Max: 70
  Exclude:
    - 'spec/controllers/**/*'
    - 'spec/routing/**/*'

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false



Metrics/TrailingWhitespace:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

  



Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 65

Metrics/PerceivedComplexity:
  Enabled: false



RSpec/ExampleLength:
  Exclude:
    - 'spec/views/games/edit.html.erb_spec.rb'
    - 'spec/views/games/new.html.erb_spec.rb'
    - 'spec/views/pieces/edit.html.erb_spec.rb'
    - 'spec/views/pieces/index.html.erb_spec.rb'
    - 'spec/views/pieces/new.html.erb_spec.rb'
    - 'spec/views/pieces/show.html.erb_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/views/games/edit.html.erb_spec.rb'
    - 'spec/views/pieces/edit.html.erb_spec.rb'
    - 'spec/views/users/edit.html.erb_spec.rb'

RSpec/MultipleExpectations:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

RSpec/MultipleDescribes:
  Enabled: false
