inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/schema.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Metrics/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Style/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    