# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d3168b398b1a3259230fda7a55843405916a16f0804c989fcb8315ef2ce4c5278958236dad0fd641299ebabec802ff8a8d2779291f89fe97d78978f96c2d442

test:
  secret_key_base: acdc9b9f566cab0b472bd93327673363b2773b085cf816d55bde66ac29205b4123ed3112ca587ce91ca2752cbfe944a8365a3679154c0f9113de9eb1b0cb1ea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
